-- Datos de prueba opcionales (ejecutar manualmente después del esquema)
--
-- 1) Aprobar institución de prueba (reemplaza YOUR_USER_UUID):
-- update public.profiles set role = 'institution' where id = 'YOUR_USER_UUID';
-- insert into public.institutions (profile_id, name, official_domain, category, zone, status, reviewed_at)
-- values ('YOUR_USER_UUID', 'Obras Públicas Demo', 'publicworks.gov', 'pothole', 'zone_1', 'approved', now())
-- on conflict (profile_id) do update set status = 'approved', reviewed_at = now();
--
-- 2) Reporte demo (reemplaza CIVILIAN_UUID e INSTITUTION_UUID):
-- insert into public.reports (title, description, category, priority, latitude, longitude, civilian_user_id, institution_id, status)
-- values ('Bache demo', 'Bache grande en calle principal', 1, 2, 19.432600, -99.133200, 'CIVILIAN_UUID', 'INSTITUTION_UUID', 0);
